routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PartyController;
use App\Http\Controllers\MeterController;
use App\Http\Controllers\ConnectionController;
use App\Http\Controllers\ConnectionChargeController;
use App\Http\Controllers\CreateBillController;
use App\Http\Controllers\ExpencesAccountController;
use App\Http\Controllers\ExpencesBillController;
use App\Http\Controllers\CustomBillController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ConnectionType;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\NocController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\DailyReportController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');

})->name('home');;


// Route::get('/dashboard', function () {
//     // return view('dashboard');
// })->middleware(['auth'])->name('dashboard');
//  Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth','2fa'])->name('dashboard');
 Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth'])->name('dashboard');

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){

    Route::resource('/party', PartyController::class);
    Route::resource('/meter', MeterController::class);
    Route::resource('/conn', ConnectionController::class);
    Route::resource('/createbill', CreateBillController::class);
    Route::get('/conndetails/{id}', [ConnectionController::class,'details'])->name('conndetails');
    Route::get('charges',[ConnectionChargeController::class, 'index'])->name('charge');
    Route::post('savecharge',[ConnectionChargeController::class, 'store'])->name('savecharge');
    Route::get('/viewbill/{id}', [CreateBillController::class,'viewbill'])->name('viewbill');
    // Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');
    Route::post('adminbillpay', [CreateBillController::class,'adminbillpay'])->name('adminbillpay');
    Route::get('/billbyconn/{id}', [CreateBillController::class,'billbyconn'])->name('billbyconn');
    Route::resource('/expensesaccount', ExpencesAccountController::class);
    // Route::get('/expencesbill/{id}', [ExpencesAccountController::class,'expencesbill'])->name('expencesbill');
    Route::resource('/expencesbill', ExpencesBillController::class);
    Route::get('/expencesbilllist/{id}', [ExpencesBillController::class,'list'])->name('expencesbilllist');
    Route::resource('/custombill', CustomBillController::class);
    Route::resource('/conn-type', ConnectionType::class);
    Route::post('custombillpay', [CreateBillController::class,'custombillpay'])->name('custombillpay');
    Route::get('adminprofile', [HomeController::class,'viewprofile'])->name('adminprofile');
    Route::post('settlement', [PartyController::class,'settlement'])->name('settlement');
    Route::get('settlement/{id}', [PartyController::class,'settlementdetail'])->name('settlementdetail');
    Route::post('updateprofile', [HomeController::class,'updateprofile'])->name('updateprofile');
    Route::get('reports', [ExpencesBillController::class,'reports'])->name('reports');
    Route::post('viewreport', [ExpencesBillController::class,'viewreport'])->name('viewreport');
    Route::get('noclist', [NocController::class,'noclist'])->name('noclist');
    Route::get('shownoc/{id}', [NocController::class,'show'])->name('shownoc');
    Route::post('update-noc', [NocController::class,'update_noc'])->name('update-noc');
    Route::get('downloadnoc/{id}', [NocController::class,'createPDF'])->name('downloadnoc');
    Route::get('transactions', [HomeController::class,'transactions'])->name('transactions');
    Route::get('seeall', [NocController::class,'seeall'])->name('seeall');
    Route::get('updatenoti', [NocController::class,'updatenoti'])->name('updatenoti');
    Route::post('getemailbyconn', [ConnectionController::class,'getemailbyconn'])->name('getemailbyconn');
    Route::get('seeallexpances', [ExpencesAccountController::class,'seeallexpances'])->name('seeallexpances');
    Route::post('getallexpances', [ExpencesAccountController::class,'getallexpances'])->name('getallexpances');
    Route::post('getslectbox', [ConnectionType::class,'getslectbox'])->name('getslectbox');
    Route::post('chequeedit', [CreateBillController::class,'chequeedit'])->name('chequeedit');
    Route::resource('counter', DailyReportController::class);
    Route::post('applynoc', [NocController::class,'applynoc'])->name('applynoc');
    Route::get('ledger', [ConnectionController::class,'ledger'])->name('ledger');


});
Route::get('conn-type',[ConnectionType::class, 'index'])->middleware(['auth'])->name('conn-type');
Route::get('party',[PartyController::class, 'index'])->middleware(['auth'])->name('party');
Route::get('meter',[MeterController::class, 'index'])->middleware(['auth'])->name('meter');
Route::get('conn',[ConnectionController::class, 'index'])->middleware(['auth'])->name('conn');
Route::get('createbill',[CreateBillController::class, 'index'])->middleware(['auth'])->name('createbill');
Route::get('paybill',[CreateBillController::class, 'paybill'])->middleware(['auth'])->name('paybill');
Route::post('getconnection',[ConnectionController::class, 'getconnection'])->middleware(['auth'])->name('getconnection');
Route::post('getconnectionbyparty',[ConnectionController::class, 'getconnectionbyparty'])->middleware(['auth'])->name('getconnectionbyparty');
Route::post('getconnectionbyconn',[ConnectionController::class, 'getconnectionbyconn'])->middleware(['auth'])->name('getconnectionbyconn');
Route::get('partybill',[ConnectionController::class, 'partybill'])->middleware(['auth'])->name('partybill');
Route::post('getallconnection',[ConnectionController::class, 'getallconnection'])->middleware(['auth'])->name('getallconnection');
Route::post('getbilldetail', [CreateBillController::class,'getbilldetail'])->name('getbilldetail');
Route::get('/expensesaccount', [ExpencesAccountController::class,'index'])->name('expensesaccount');
Route::get('/expencesbill', [ExpencesBillController::class,'index'])->name('expencesbill');
Route::get('/custombill', [CustomBillController::class,'index'])->name('custombill');
Route::get('/complete-registration', [RegisteredUserController::class,'completeRegistration']);
Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');
Route::get('/login', [CustomerController::class, 'index'])
                ->middleware('guest')
                ->name('login');
Route::post('/customerlogin', [CustomerController::class, 'login'])
                ->middleware('guest')
                ->name('customerlogin');

Route::group(['prefix'=>'customer','middleware'=>['customer']],function(){
    Route::get('/dashboard', [HomeController::class,'customerdashboard']);
    Route::get('bill/{id?}/', [HomeController::class,'customerbill']);
    Route::get('paynow/{id}/', [PaymentController::class,'paynnow']);
    Route::resource('noc', NocController::class);
    Route::get('records/{id?}', [CustomerController::class,'records']);
    Route::get('downloadnoc/{id}', [NocController::class,'downloadnoc'])->name('downloadnoc');
    Route::get('profile', [CustomerController::class,'profile'])->name('profile');
    Route::post('updateprofile', [CustomerController::class,'updateprofile'])->name('updateprofile');
    // Route::get('verifymail/{email}', [CustomerController::class,'verifymail'])->name('verifymail');
    Route::post('updatedata', [CustomerController::class,'updatedata'])->name('updatedata');
    Route::post('resend', [CustomerController::class,'resend'])->name('resend');
    // Route::get('verifymobile/{mobile}', [CustomerController::class,'verifymobile'])->name('verifymobile');
    Route::get('shownocc/{id}', [NocController::class,'customershownoc'])->name('shownocc');
    Route::get('checkmail', [CustomerController::class,'checkmail'])->name('checkmail');
    Route::get('checkmob', [CustomerController::class,'checkmob'])->name('checkmob');
    Route::get('/viewrecipts/{id}', [HomeController::class,'viewrecipt'])->name('viewrecipt');
    Route::get('newconn', [HomeController::class,'newconn'])->name('newconn');


});
Route::get('/customer-reg', [CustomerController::class, 'registration'])
                ->middleware('guest')
                ->name('customer-reg');
Route::get('/cu-reg', [CustomerController::class, 'register'])
->middleware('guest')
->name('cu-reg');

Route::get('/housing-reg', [CustomerController::class, 'housing_register'])
->middleware('guest')
->name('housing-reg');

Route::post('/storecustomer', [CustomerController::class, 'store'])
->middleware('guest')
->name('storecustomer');
Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');


// Route::post('subscribe-cancel', [
//     'as' => 'subscribe-cancel',
//     'uses' => 'PaymentController@SubscribeCancel'
// ]);

// Route::post('subscribe-response', [
//     'as' => 'subscribe-response',
//     'uses' => 'PaymentController@SubscribeResponse'
// ]);
Route::post('subscribe-response', [PaymentController::class,'SubscribeResponse']);
Route::get('/paysuccess', [PaymentController::class,'paysuccess'])->name('paysuccess');
Route::get('/sendmail', [EmailController::class,'sendmail'])->name('sendmail');
Route::get('/verifyemail', [EmailController::class,'verifyemail'])->name('verifyemail');
Route::post('/confirmemail', [EmailController::class,'confirmemail'])->name('confirmemail');

app/Models/ExpencesAccount.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ExpencesAccount extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'credit',
        'debit',
    ];
}

app/Http/Controllers/ExpencesAccountController.php
<?php

namespace App\Http\Controllers;

use App\Models\ExpencesAccount;
use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Facades\Validator;
use App\Models\ExpencesBill;
use Carbon\Carbon;
class ExpencesAccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accounts = ExpencesAccount::orderBy('id', 'DESC')->get();
        $today = ExpencesBill::whereDate('created_at', Carbon::today())->sum('amount');
        $month = ExpencesBill::whereMonth('created_at', date('m'))->whereYear('created_at', date('Y'))->sum('amount');
        $year = ExpencesBill::whereYear('created_at', date('Y'))->sum('amount');
        return view('expencesaccount.list',['year'=>$year,'month'=>$month,'today'=>$today,'accounts'=>$accounts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { 
        return view('expencesaccount.add');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name' => 'required|string|max:255|unique:expences_accounts,name',
            ])->validate();

            $accountid = ExpencesAccount::create([
                'name' => $request->name,
            ]);

            return redirect()->route('expensesaccount')->with('status', 'Account added  succesfully');
       

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ExpencesAccount  $expencesAccount
     * @return \Illuminate\Http\Response
     */
    public function show(ExpencesAccount $expencesAccount)
    {
        return view('expencesaccount.show',['expencesAccount'=>$expencesAccount]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ExpencesAccount  $expencesAccount
     * @return \Illuminate\Http\Response
     */
    public function edit(ExpencesAccount $expencesAccount)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ExpencesAccount  $expencesAccount
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ExpencesAccount $expencesAccount)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ExpencesAccount  $expencesAccount
     * @return \Illuminate\Http\Response
     */
    public function destroy(ExpencesAccount $expencesAccount)
    {
        //
    }

    public function seeallexpances()
    { 
        $accounts = ExpencesAccount::all();
        return view('expencesaccount.viewall',['accounts'=>$accounts]);

    }


    public function getallexpances(Request $request)
    {
        
        //   dd($request);
        // DB::enableQueryLog();
        $exp =  ExpencesBill::query();
        if ($request->party != null) {
            $exp =  $exp->where('expances_account_id',$request->party);

        }
        if ($request->month != null) {
            $exp =  $exp->whereMonth('created_at', $request->month);
        }
        if ($request->year != null) {
            $exp = $exp->whereYear('created_at', $request->year);
        }else{
            $exp = $exp->whereYear('created_at', date('Y'));

        }
       
        // if ($request->party_id != null) {
            $data =  $exp->get()->load('acc');
            // $data = $conn->get()->load('custom_bills');

        // }else{
        //     $data = $conn->get();
        // }


// and then you can get query log

        echo  json_encode($data);
         exit;
      
    }
   

}

resources/views/expencesaccount/add.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="row">
         <div class="col-md-10">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
               {{ __('Expences Account') }}
            </h2>
         </div>
         <div class="col-md-2">
            <a class="btn btn-primary" href="{{ route('expensesaccount') }}">
            {{ __('Expences Account List') }}
            </a>
         </div>
      </div>
   </x-slot>
   <div class="py-12">
      <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
         <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6 bg-white border-b border-gray-200">
               <x-auth-validation-errors class="mb-4" :errors="$errors" />
               <fieldset class="scheduler-border">
                  <legend class="scheduler-border">Expences Account:</legend>
                  <form method="POST" action="{{ route('expensesaccount.store') }}">
                     @csrf
                     <div class="form-row">
                        <!-- Name -->
                        <div class="mt-4 col">
                           <x-label for="name" :value="__('Name')" />
                           <x-input id="name" class="block mt-1 w-full" type="text" name="name" :value="old('name')" required autofocus />
                        </div>
                     <div class="flex items-center justify-end mt-4">
                        <x-button class="ml-4">
                           {{ __('Save') }}
                        </x-button>
                     </div>
                  </form>
               </fieldset>
            </div>
         </div>
      </div>
   </div>
</x-app-layout>

resources/views/expencesaccount/addbill.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="row">
         <div class="col-md-10">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
               {{ __('Expences Account') }}
            </h2>
         </div>
         <div class="col-md-2">
            <a class="btn btn-primary" href="{{ route('expensesaccount') }}">
            {{ __('Expences Account List') }}
            </a>
         </div>
      </div>
   </x-slot>
   <div class="py-12">
      <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
         <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6 bg-white border-b border-gray-200">
               <x-auth-validation-errors class="mb-4" :errors="$errors" />
               <fieldset class="scheduler-border">
                  <legend class="scheduler-border">Add Bill:</legend>
                  <form method="POST" action="{{ route('expencesbill.store') }}">
                     @csrf
                     <div class="form-row">
                        <!-- Name -->
                        <input type="hidden" value="{{$expances_account_id}}" name="expances_account_id"/>
                        <div class="mt-4 col-md-4">
                           <x-label for="bill_no" :value="__('Bill No')" />
                           <x-input id="bill_no" class="block mt-1 w-full" type="text" name="bill_no" :value="old('bill_no')" required autofocus />
                        </div>
                        <div class="mt-4 col-md-4">
                           <x-label for="amount" :value="__('Amount')" />
                           <x-input id="amount" class="block mt-1 w-full" type="number" name="amount" :value="old('amount')" required  />
                        </div>
                        <div class="mt-4 col-md-4">
                        <x-label for="paid_by" :value="__('Paid Through')" />
                        <select id="paid_by" class="form-control" name="paid_by" required>
                           <option value="">Choose...</option>
                           <option value="cash">Cash</option>
                           <option value="cheque">Cheque</option>
                        </select>
                      </div>
                      <div class="mt-4 col">
                        <x-label for="check_no" :value="__('Cheque No')" />
                        <x-input id="check_no" class="block mt-1 w-full"
                           type="number" disabled   name="check_no" :value="old('check_no')"    />
                     </div>
                        <div class="mt-4 col-md-8">
                           <x-label for="description" :value="__('Description')" />
                           <textarea id="description" class="block mt-1 w-full form-control"  name="description"  required >{{old('description')}}</textarea>
                        </div>
                     <div class="flex items-center justify-end mt-4">
                        <x-button class="ml-4">
                           {{ __('Save') }}
                        </x-button>
                     </div>
                  </form>
               </fieldset>
            </div>
         </div>
      </div>
   </div>
   <script>
         $('#paid_by').change(function(){
var unit =$(this).val();
if(unit=='cheque'){
   $("#check_no").removeAttr("disabled"); 

}else{
   $("#check_no").attr('disabled','disabled');

}
});
   </script>
</x-app-layout>

resources/views/expencesaccount/billlist.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="row">
    <div class="col-md-10">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Expences Account') }}
        </h2>
        </div>
        <div class="col-md-2">
        <a class="btn btn-primary" href="{{ route('expensesaccount') }}">
                        {{ __('Back') }}
                    </a>
        </div>
        </div>
    </x-slot>
    <div class="col-md-12">
    <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-3" style="position:absolute; right:0">
    @if (session('status'))
      <div class="alert alert-success">
          <p class="msg"> <?php echo  session("status"); ?></p>
      </div>
    @endif
     </div>
     </div></div>
    <div class="col-md-12">
 
    <div class="py-12">
    <div class="col-md-12">
    <div class="row">
    <div class="col-md-10">
        
        </div>
        <div class="col-md-2 mb-2">
       
        </div>
        </div>
        </div>
        <div class="py-12 bg-white max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg table-responsive">
            <div class="row"><div class="col-md-3">
           
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            <a class="btn btn-primary" href="{{ route('expencesbill.show',$account->id) }}">
        <i class="fa fa-plus" aria-hidden="true"></i>
                    </a> {{$account->name }}
        </h2>
            </div>
            <div class="col-md-3 text-left">
            <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Expances till month: &nbsp;<b> {{$month}}</b></li>
  </ul>
</div>
             </div>
             <div class="col-md-3 text-left">
            <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Expances of today: &nbsp;&nbsp;&nbsp;<b> {{$today}}</b></li>
  </ul>
</div>
             </div>
            <div class="col-md-3 mb-3 text-left">
            <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Expances till year:&nbsp;&nbsp;&nbsp; <b> {{$year}}</b></li>
  </ul>
</div>
             </div>
            </div>
            <table class="table" id="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Bill No</th>
      <th scope="col">Date</th>
      <th scope="col">Description</th>
      <th scope="col">Amount</th>
      <th scope="col">Pay Through</th>
      <th scope="col">Added By</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  @php $i=1; @endphp
  @foreach($billdatas as $billdata)
    <tr>
      <th scope="row">{{$i++}}</th>
      <td>{{$billdata->bill_no}}</td>
      <td>{{$billdata->created_at}}</td>
      <td>{{$billdata->description}}</td>
      <td>{{$billdata->amount}}</td>
      <td>{{$billdata->paid_by}}</td>
      <td>{{$billdata->user->name}}</td>
     <td><a href="#"  data-toggle="modal" data-target="#{{$i}}"><i class="fa fa-eye" aria-hidden="true"></i></a> | <a href="{{route('expencesbill.edit',$billdata->id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a> </td>
    </tr>
    <div class="modal fade" id="{{$i}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Expances Infromation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <div class="form-row">
      <div class="col-md-6"><span><b>Bill No:</b>  {{$billdata->bill_no}}</span></div>
      <div class="col-md-6"><span><b>Date:</b>  {{$billdata->created_at}}</span></div>
      <div class="col-md-6"><span><b>Amount:</b>  {{$billdata->amount}}</span></div>
      <div class="col-md-6"><span><b>Billing month:</b>  {{date('M',strtotime($billdata->created_at))}}</span></div>
   
<div class="col-md-6"><span ><b>Payment :</b> {{$billdata->paid_by}}</span></div>
      <div class="col-md-6"><span ><b>Checqe No :</b> {{$billdata->check_no}}</span></div>
       </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
    @endforeach
  </tbody>
</table>
             
            </div>
        </div>
    </div>

    <script>
      // jQuery.noConflict();
    jQuery(document).ready(function(e) {
      e.noConflict();
      jQuery('#table').DataTable();
      jQuery('.alert-success').hide('slide', {direction: 'right'}, 10000);

} );
    </script>
</x-app-layout>

resources/views/expencesaccount/list.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="row">
    <div class="col-md-10">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Expences Account') }}
        </h2>
        </div>
        <div class="col-md-2">
        <a class="btn btn-primary" href="{{ route('expensesaccount.create') }}">
                        {{ __('Add Expences Account') }}
                    </a>
        </div>
        </div>
    </x-slot>
    <div class="col-md-12">
    <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-3" style="position:absolute; right:0">
    @if (session('status'))
      <div class="alert alert-success">
          <p class="msg"> <?php echo  session("status"); ?></p>
      </div>
    @endif
     </div>
     </div></div>
    <div class="py-12">

        <div class="py-12 bg-white max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg table-responsive">
            <div class="row">
            <div class="col-md-3 text-center">
            <div class="card" style="width: 10rem;">
<a href="/admin/seeallexpances" class="btn btn-lg btn-success">Get Records</a>
</div>
           </div>
            <div class="col-md-3 mb-3 text-left"> 
            <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Expances till month: &nbsp;<b> {{$month}}</b></li>
  </ul>
</div>     
            </div>
            <div class="col-md-3 text-center">
            <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Expances of today: &nbsp;&nbsp;&nbsp;<b> {{$today}}</b></li>
  </ul>
</div>
           </div>

           
            <div class="col-md-3 mb-3 text-left">
            <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Expances till year:&nbsp;&nbsp;&nbsp; <b> {{$year}}</b></li>
  </ul>
</div>

            </div>
            </div>
            <table class="table" id="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  @php $i=1; @endphp
  @foreach($accounts as $account)
    <tr>
      <th scope="row">{{$i++}}</th>
      <td>{{$account->name}}</td>
     <td><a href="{{route('expencesbill.show',$account->id)}}"><i class="fa fa-plus" aria-hidden="true"></i></a> |  <a href="{{route('expencesbilllist',$account->id)}}"><i class="fa fa-eye" aria-hidden="true"></i></a> </td>
    </tr>

    @endforeach
  </tbody>
</table>
             
            </div>
        </div>
    </div>

    <script>
      // jQuery.noConflict();
    jQuery(document).ready(function(e) {
      e.noConflict();
      jQuery('#table').DataTable();
      $('.alert-success').hide('slide', {direction: 'right'}, 10000);

} );
    </script>
</x-app-layout>

resources/views/expencesaccount/show.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="row">
    <div class="col-md-10">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Connections Show') }}
        </h2>
        </div>
        <div class="col-md-2">
        <a class="btn btn-primary" href="{{ route('conn') }}">
                        {{ __('Connections List') }}
                    </a>
        </div>
        </div>
    </x-slot>
    <div class="py-12">     
        <div class="py-12 bg-white max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg table-responsive">
   <div class="col-md-12">

<table id="table" class="table table-bordered">
    <thead class="thead-light">
    <tr><th class="text-center" colspan=10>Party Name : {{$party->name}}</th></tr>
    <tr><th class="text-center" colspan=10>Connection Details</th></tr>
      <tr>
      <th>#</th>
        <th>Connection No</th>
        <th>Bills</th>
        <th>Name</th>
        <th>Address</th>
        <th>Status</th>
        <th>Email</th>
        <th>Phone NO</th>
        <th>Debit</th>
        <th>Credit</th>
      </tr>
    </thead>
    <tbody>
    @php $i=1 @endphp
    @foreach($party->conn as $connection)
      <tr>
      <td>{{$i++ }}</td>
        <td>{{$connection->conn_no}}</td>
        <td>@if (isset($connection->mybill)) {{$connection->mybill->count()}} @else 0  @endif</td>
        <td><a href="{{route('conndetails',$connection->id)}}">{{$connection->name}}</a></td>
        <td>{{$connection->address}}</td>
        <td>{{$connection->status}}</td>
        <td>{{$connection->email}}</td>
        <td>{{$connection->phone}}</td>
        <td>{{$connection->debit}}</td>
        <td>{{$connection->credit}}</td>
      </tr>
@endforeach
    </tbody>
  </table>


            </div>
        </div>
    </div>
    <script>
 
      //  jQuery.noConflict();
      jQuery(document).ready(function(e) {
      // e.noConflict();
      jQuery('#table').DataTable();

            $('.alert-success').hide('slide', {direction: 'right'}, 4000);
      
} );


    </script>
</x-app-layout>