routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PartyController;
use App\Http\Controllers\MeterController;
use App\Http\Controllers\ConnectionController;
use App\Http\Controllers\ConnectionChargeController;
use App\Http\Controllers\CreateBillController;
use App\Http\Controllers\ExpencesAccountController;
use App\Http\Controllers\ExpencesBillController;
use App\Http\Controllers\CustomBillController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ConnectionType;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\NocController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\DailyReportController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');

})->name('home');;


// Route::get('/dashboard', function () {
//     // return view('dashboard');
// })->middleware(['auth'])->name('dashboard');
//  Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth','2fa'])->name('dashboard');
 Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth'])->name('dashboard');

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){

    Route::resource('/party', PartyController::class);
    Route::resource('/meter', MeterController::class);
    Route::resource('/conn', ConnectionController::class);
    Route::resource('/createbill', CreateBillController::class);
    Route::get('/conndetails/{id}', [ConnectionController::class,'details'])->name('conndetails');
    Route::get('charges',[ConnectionChargeController::class, 'index'])->name('charge');
    Route::post('savecharge',[ConnectionChargeController::class, 'store'])->name('savecharge');
    Route::get('/viewbill/{id}', [CreateBillController::class,'viewbill'])->name('viewbill');
    // Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');
    Route::post('adminbillpay', [CreateBillController::class,'adminbillpay'])->name('adminbillpay');
    Route::get('/billbyconn/{id}', [CreateBillController::class,'billbyconn'])->name('billbyconn');
    Route::resource('/expensesaccount', ExpencesAccountController::class);
    // Route::get('/expencesbill/{id}', [ExpencesAccountController::class,'expencesbill'])->name('expencesbill');
    Route::resource('/expencesbill', ExpencesBillController::class);
    Route::get('/expencesbilllist/{id}', [ExpencesBillController::class,'list'])->name('expencesbilllist');
    Route::resource('/custombill', CustomBillController::class);
    Route::resource('/conn-type', ConnectionType::class);
    Route::post('custombillpay', [CreateBillController::class,'custombillpay'])->name('custombillpay');
    Route::get('adminprofile', [HomeController::class,'viewprofile'])->name('adminprofile');
    Route::post('settlement', [PartyController::class,'settlement'])->name('settlement');
    Route::get('settlement/{id}', [PartyController::class,'settlementdetail'])->name('settlementdetail');
    Route::post('updateprofile', [HomeController::class,'updateprofile'])->name('updateprofile');
    Route::get('reports', [ExpencesBillController::class,'reports'])->name('reports');
    Route::post('viewreport', [ExpencesBillController::class,'viewreport'])->name('viewreport');
    Route::get('noclist', [NocController::class,'noclist'])->name('noclist');
    Route::get('shownoc/{id}', [NocController::class,'show'])->name('shownoc');
    Route::post('update-noc', [NocController::class,'update_noc'])->name('update-noc');
    Route::get('downloadnoc/{id}', [NocController::class,'createPDF'])->name('downloadnoc');
    Route::get('transactions', [HomeController::class,'transactions'])->name('transactions');
    Route::get('seeall', [NocController::class,'seeall'])->name('seeall');
    Route::get('updatenoti', [NocController::class,'updatenoti'])->name('updatenoti');
    Route::post('getemailbyconn', [ConnectionController::class,'getemailbyconn'])->name('getemailbyconn');
    Route::get('seeallexpances', [ExpencesAccountController::class,'seeallexpances'])->name('seeallexpances');
    Route::post('getallexpances', [ExpencesAccountController::class,'getallexpances'])->name('getallexpances');
    Route::post('getslectbox', [ConnectionType::class,'getslectbox'])->name('getslectbox');
    Route::post('chequeedit', [CreateBillController::class,'chequeedit'])->name('chequeedit');
    Route::resource('counter', DailyReportController::class);
    Route::post('applynoc', [NocController::class,'applynoc'])->name('applynoc');
    Route::get('ledger', [ConnectionController::class,'ledger'])->name('ledger');


});
Route::get('conn-type',[ConnectionType::class, 'index'])->middleware(['auth'])->name('conn-type');
Route::get('party',[PartyController::class, 'index'])->middleware(['auth'])->name('party');
Route::get('meter',[MeterController::class, 'index'])->middleware(['auth'])->name('meter');
Route::get('conn',[ConnectionController::class, 'index'])->middleware(['auth'])->name('conn');
Route::get('createbill',[CreateBillController::class, 'index'])->middleware(['auth'])->name('createbill');
Route::get('paybill',[CreateBillController::class, 'paybill'])->middleware(['auth'])->name('paybill');
Route::post('getconnection',[ConnectionController::class, 'getconnection'])->middleware(['auth'])->name('getconnection');
Route::post('getconnectionbyparty',[ConnectionController::class, 'getconnectionbyparty'])->middleware(['auth'])->name('getconnectionbyparty');
Route::post('getconnectionbyconn',[ConnectionController::class, 'getconnectionbyconn'])->middleware(['auth'])->name('getconnectionbyconn');
Route::get('partybill',[ConnectionController::class, 'partybill'])->middleware(['auth'])->name('partybill');
Route::post('getallconnection',[ConnectionController::class, 'getallconnection'])->middleware(['auth'])->name('getallconnection');
Route::post('getbilldetail', [CreateBillController::class,'getbilldetail'])->name('getbilldetail');
Route::get('/expensesaccount', [ExpencesAccountController::class,'index'])->name('expensesaccount');
Route::get('/expencesbill', [ExpencesBillController::class,'index'])->name('expencesbill');
Route::get('/custombill', [CustomBillController::class,'index'])->name('custombill');
Route::get('/complete-registration', [RegisteredUserController::class,'completeRegistration']);
Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');
Route::get('/login', [CustomerController::class, 'index'])
                ->middleware('guest')
                ->name('login');
Route::post('/customerlogin', [CustomerController::class, 'login'])
                ->middleware('guest')
                ->name('customerlogin');

Route::group(['prefix'=>'customer','middleware'=>['customer']],function(){
    Route::get('/dashboard', [HomeController::class,'customerdashboard']);
    Route::get('bill/{id?}/', [HomeController::class,'customerbill']);
    Route::get('paynow/{id}/', [PaymentController::class,'paynnow']);
    Route::resource('noc', NocController::class);
    Route::get('records/{id?}', [CustomerController::class,'records']);
    Route::get('downloadnoc/{id}', [NocController::class,'downloadnoc'])->name('downloadnoc');
    Route::get('profile', [CustomerController::class,'profile'])->name('profile');
    Route::post('updateprofile', [CustomerController::class,'updateprofile'])->name('updateprofile');
    // Route::get('verifymail/{email}', [CustomerController::class,'verifymail'])->name('verifymail');
    Route::post('updatedata', [CustomerController::class,'updatedata'])->name('updatedata');
    Route::post('resend', [CustomerController::class,'resend'])->name('resend');
    // Route::get('verifymobile/{mobile}', [CustomerController::class,'verifymobile'])->name('verifymobile');
    Route::get('shownocc/{id}', [NocController::class,'customershownoc'])->name('shownocc');
    Route::get('checkmail', [CustomerController::class,'checkmail'])->name('checkmail');
    Route::get('checkmob', [CustomerController::class,'checkmob'])->name('checkmob');
    Route::get('/viewrecipts/{id}', [HomeController::class,'viewrecipt'])->name('viewrecipt');
    Route::get('newconn', [HomeController::class,'newconn'])->name('newconn');


});
Route::get('/customer-reg', [CustomerController::class, 'registration'])
                ->middleware('guest')
                ->name('customer-reg');
Route::get('/cu-reg', [CustomerController::class, 'register'])
->middleware('guest')
->name('cu-reg');

Route::get('/housing-reg', [CustomerController::class, 'housing_register'])
->middleware('guest')
->name('housing-reg');

Route::post('/storecustomer', [CustomerController::class, 'store'])
->middleware('guest')
->name('storecustomer');
Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');


// Route::post('subscribe-cancel', [
//     'as' => 'subscribe-cancel',
//     'uses' => 'PaymentController@SubscribeCancel'
// ]);

// Route::post('subscribe-response', [
//     'as' => 'subscribe-response',
//     'uses' => 'PaymentController@SubscribeResponse'
// ]);
Route::post('subscribe-response', [PaymentController::class,'SubscribeResponse']);
Route::get('/paysuccess', [PaymentController::class,'paysuccess'])->name('paysuccess');
Route::get('/sendmail', [EmailController::class,'sendmail'])->name('sendmail');
Route::get('/verifyemail', [EmailController::class,'verifyemail'])->name('verifyemail');
Route::post('/confirmemail', [EmailController::class,'confirmemail'])->name('confirmemail');

resources/views/bills/allbills.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="row">
    <div class="col-md-10">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Bill') }}
        </h2>
        </div>
        <div class="col-md-2">
        <a class="btn btn-primary" href="{{ route('createbill.create') }}">
                        {{ __('Add Bill') }}
        </a>
        <input type="button" class="btn btn-primary" value="Print" onclick="pdf()" />

        </div>
        </div>
        <link rel="stylesheet" href="https://cdn.datatables.net/datetime/1.1.0/css/dataTables.dateTime.min.css">

    </x-slot>
    <div class="py-12">

        <div class="py-12 bg-white max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg table-responsive">
            <table border="0" cellspacing="5" cellpadding="5">
        <tbody>
        <tr>
            <td>From date:</td>
            <td><input type="text" id="min" name="min"></td>
            <td>To date:</td>
            <td><input type="text" id="max" name="max"></td>
        </tr>
    </tbody>
    </table>
    <div id="print-window">
            <table class="table" id="table">
  <thead class="thead-light">
  <tr><th class="text-center" colspan=10 scope="col">Party Name :  {{$connection->party->name}} , {{$connection->conn_no}}</th></tr>
    <tr><th class="text-center" colspan=10 scope="col">Connection Details</th></tr>
 
    <tr>
      <th scope="col">Bill Date</th>
      <th scope="col">Bill No</th>
      <!-- <th scope="col">Bill Type</th> -->
      <th scope="col">Bill Month</th>
      <th scope="col">Consume Unit</th>
      <th scope="col">Bill Amt</th>
      <th scope="col">Status</th>
        <th scope="col">Paid Amt</th>
    <th scope="col">Paid Date</th>
      <th scope="col">Txn No</th>
      <th scope="col">Balance</th>
   </tr>

  </thead>
  <tbody>
  @php $i=0; $paidamt =0; $unpaidamt=0; $cusarray = []@endphp
 @php $numItems = count($bills); @endphp
  @foreach($bills as $bill)
  @php ++$i @endphp
    <tr>
      <th scope="row">{{date('Y/m/d',strtotime($bill->created_at))}}</th>
      <th scope="row">{{$bill->id}}</th>
      <!-- <td>Manual</td> -->
     <td>{{$bill->billing_month}}</td>
      <td>{{$bill->consume_unit}}</td>
      <td>{{$bill->bill_to_pay}}</td>
      @if($bill->paid_status=='paid')
      @if($bill->paid_date!=null)
      <td class="text-success"><b>{{ucwords($bill->paid_status)}}</b></td>
          @php $paidamt+=$bill->paid_amount;  @endphp
      @else
        <td class="text-primary"><b>Shifted</b></td>
      @endif

      @else
      
      @if($i === $numItems) 
      <td class="text-danger"><b>{{ucwords($bill->paid_status)}}</b></td>
         
      @php $unpaid=$bill->total;  @endphp
     @else
     <td class="text-primary"><b>Shifted</b></td>
       @endif

      @endif
      @if($bill->paid_amount)
      <td>{{$bill->paid_amount}}</td>
      @else
      <td>N/A</td>
      @endif
      @if($bill->paid_date)
      <td>{{date('d-m-Y',strtotime($bill->paid_date))}}</td>
       @else
       <td>N/A</td>
       @endif
      @if($bill->paid_status=='paid')
      <td>Txn-{{$bill->id}}</td>
      @else

      <td>N/A</td>
      @endif
      @if($bill->paid_status=='paid')
      @if($bill->bill_credit>0)
      @php $amt = $bill->bill_credit .' CR' @endphp
      @else
      @php $amt = $bill->bill_debit .' DR' @endphp
      @endif
      <td><b>{{$amt}}</b></td>
      @else
      <td><b>{{$bill->total}} DR </b></td>
      @endif

    </tr>
        @endforeach
     
       @php $mainarray=[]; @endphp
        @foreach($custom_bills as $custom_bill)
    <tr>
    <th scope="row">{{date('d-m-Y',strtotime($custom_bill->created_at))}}</th>
      <td>{{$custom_bill->voucher_no}}</td>
   <td>@if(isset($custom_bill->conn->conn_no)){{$custom_bill->conn->conn_no}}@else xxxxxx @endif</td>
      <!-- <td>Custom</td> -->
     <td>{{date('M-Y',strtotime($custom_bill->created_at))}}</td>
      <td></td>
      <td>{{$custom_bill->total}}</td>
@if($custom_bill->paid_status=='paid')
      @if(!in_array('paid',$mainarray))
      <td>{{$custom_bill->paid_status}}</td>
          @php $paidamt+=$custom_bill->total; $mainarray[]=$custom_bill->paid_status; @endphp
      @else
        <td>shifted</td>
      @endif

      @else
      @if(!in_array('unpaid',$mainarray))
      <td>{{$custom_bill->paid_status}}</td>
      @else
        <td>shifted</td>
        @endif
      @endif
    </tr>
        @endforeach
        </tbody>
        <tfoot>
    <tr>
    <th></th>
      <th colspan="2" >Total Paid
      {{$paidamt}} INR </th>
      <th></th>
      <th></th>
      <th></th>
      
      <th></th>
      <th colspan="3">@if($connection->debit>0)
      Current Balance Amount :{{$connection->debit}} DR @else Current Balance Amount: {{$connection->credit}} CR @endif</th>
      <th></th> </tr>
  </tfoot>
</table>      
</div>       
            </div>
        </div>
    </div>
    <input type="hidden" id="name" value="{{$connection->name}}"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css">

    <script type="text/javascript"  src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script> 
      
      <script type="text/javascript"  src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script> 
      <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script> 
      <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script> 
      <script type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script> 
      <script type="text/javascript"  src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script> 
      <script type="text/javascript"  src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script> 
      <script type="text/javascript"  src=" https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
      <script type="text/javascript"  src="https://cdn.datatables.net/datetime/1.1.0/js/dataTables.dateTime.min.js"></script>
    <script>
          var minDate, maxDate;
 
 // Custom filtering function which will search data in column four between two values
 jQuery.fn.dataTable.ext.search.push(
     function( settings, data, dataIndex ) {
         var min = minDate.val();
         var max = maxDate.val();
         var date = new Date( data[0] );
         console.log(data);
  
         if (
             ( min === null && max === null ) ||
             ( min === null && date <= max ) ||
             ( min <= date   && max === null ) ||
             ( min <= date   && date <= max )
         ) {
             return true;
         }
         return false;
     }
 );

 jQuery.fn.dataTable.Api.register( 'sum()', function ( ) {
    return this.flatten().reduce( function ( a, b ) {
        if ( typeof a === 'string' ) {
            a = a.replace(/[^\d.-]/g, '') * 1;
        }
        if ( typeof b === 'string' ) {
            b = b.replace(/[^\d.-]/g, '') * 1;
        }
 
        return a + b;
    }, 0 );
} );
      // jQuery.noConflict();
    jQuery(document).ready(function(e) {
      e.noConflict();
      

  // Create date inputs
  minDate = new DateTime(jQuery('#min'), {
    format: 'Do MMMM YYYY'
    });
    maxDate = new DateTime(jQuery('#max'), {
        format: 'Do MMMM YYYY'
    });
 
    // DataTables initialisation
    // var table = jQuery('#table').DataTable();
 
    // Refilter the table
    jQuery('#min, #max').on('change', function () {
        table.draw();
    });
    var table=  jQuery('#table').DataTable({
  
        "pageLength": 30,
       
      
        drawCallback: function () {
      var api = this.api();
      // jQuery( api.table().footer() ).html(
      //   api.column( 7, {page:'current'} ).data().sum()
      // );
    }
      });
      
      
} );

function pdf() {
    let t = document.getElementById('print-window').innerHTML;

    let style = "<style>";
    style = style + "table {width: 100%; font-size: 17px;}";
    style = style + "table, th, td {border: solid 1px #DDD; border-collapse: collapse;";
    style = style + "padding: 2px 3px;text-align: center;}";
    style = style + "#table_info{display:none;} #table_paginate{display:none; } #table_filter{display:none; } .dt-buttons{display:none;} #table_length{display:none;} </style>";
    let win = window.open('', '', 'height=600,width=600');

    win.document.write('<html><head>');
    win.document.write('<title>Profile</title>');
    win.document.write(style);
    win.document.write('</head>');
    win.document.write('<body>');
    win.document.write(t);
    win.document.write('</body></html>');

    win.document.close();
    win.print();
}
    </script>
</x-app-layout>

resources/views/bills/list.blade.php
<x-app-layout>
    <x-slot name="header">
    <div class="row">
    <div class="col-md-10">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Bill') }}
        </h2>
        </div>
        <div class="col-md-2">
        <a class="btn btn-primary" href="{{ route('createbill.create') }}">
                        {{ __('Add Bill') }}
                    </a>
        </div>
        </div>
    </x-slot>
    <div class="col-md-12">
    <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-3" style="position:absolute; right:0">
    @if (session('status'))
      <div class="alert alert-success">
          <p class="msg"> <?php echo  session("status"); ?></p>
      </div>
    @endif
     </div>
     </div></div>
    <div class="py-12">
        <div class="py-12 bg-white max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg table-responsive">
            <table class="table" id="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Voucher No</th>
      <th scope="col">Connection No</th>
      <th scope="col">Billing Month</th>
      <th scope="col">Consume Unit</th>
      <th scope="col">Total Amount</th>
      <th scope="col">Payment Method</th>
      <th scope="col">Payment</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  @php $i=1; @endphp
  @php $connid=[] @endphp
  @foreach($bills as $bill)
  
    <tr>
      <th scope="row">{{$i++}}</th>
      <th scope="row">{{$bill->id}}</th>
      <td>@if(isset($bill->conn->conn_no)){{$bill->conn->conn_no}}@else xxxxxx @endif</td>
     <td>{{$bill->billing_month}}</td>
      <td>{{$bill->consume_unit}}</td>
      <td>{{$bill->bill_to_pay}}</td>
   {{--   <td>@if($bill->paid_status=='paid')<i class="fa fa-check-circle fa-lg" aria-hidden="true"></i>
          @else
      @php       $today =date('Y-m-d H:i:s');
                 $chdate =  date('Y-m-d H:i:s', strtotime($bill->created_at. " + 15days"));
               @endphp
      @if($today<=$chdate)<i class="fa fa-exclamation-circle fa-lg"></i>@else<i class="fa fa-times-circle fa-lg" aria-hidden="true"></i>
      @endif @endif
      </td>--}}
      <td>{{$bill->pay_by}}</td>
      <td>@if($bill->paid_status=='paid')<i class="fa fa-check-circle fa-lg" data-toggle="tooltip" data-placement="top" title="Bill is paid" aria-hidden="true"></i>
      @else @if(in_array("$bill->connections_id",$connid)) <i class="fa fa-times-circle fa-lg" data-toggle="tooltip" data-placement="top" title="Bill disclose sechedule to next" aria-hidden="true"></i>
     
      @else
      @if($bill->paid_status=='pending')<i class="fa fa-times-circle fa-lg" data-toggle="tooltip" data-placement="top" title="Bill is Pending" aria-hidden="true"></i>
       @else<i class="fa fa-exclamation-circle fa-lg" data-toggle="tooltip" data-placement="top" title="Bill due"></i> 
       @endif 
      @endif 
      @endif</td>
      @php $connid[]=$bill->connections_id   @endphp
     </td>

       <td>@if($bill->paid_status=='pending') 
       <a href="#"  data-toggle="modal" data-target="#edit{{$i}}"><i class="fa fa-trash"></i></a>
         @endif|
       @if($bill->paid_status=='unpaid')@if(Auth::user()->id=='1')<a href="{{route('createbill.edit',$bill->id)}}"><i class="fa fa-pencil" aria-hidden="true"></i></a>@endif |@endif <a href="{{route('viewbill',$bill->id)}}"><i class="fa fa-eye" aria-hidden="true"></i></a>   
    </tr>

        <!-- Modal -->
<div class="modal fade" id="{{$i}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">{{$bill->total}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <div class="form-row">
      <div class="col-md-6"><span><b>Billing Month:</b>  {{$bill->billing_month}}</span></div>
      <div class="col-md-6"><span><b>Bill Generated On:</b>  {{date('d-M-Y',strtotime($bill->created_at))}}</span></div>
      <div class="col-md-6"><span><b>Connection No:</b> @if(isset($bill->conn->conn_no)){{$bill->conn->conn_no}}@else xxxxxx @endif</span></div>
      <div class="col-md-6"><span><b>Total Unit:</b>  {{$bill->unit}}</span></div>
      <div class="col-md-6"><span><b>Consume Unit:</b> {{$bill->consume_unit}}</span></div>
      <div class="col-md-6"><span><b>Total Amount :</b> {{$bill->total}}</span></div>

       </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

 <!-- Cheque Paymnet  model  -->
 <div class="modal fade" id="edit{{$i}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                     <div class="modal-dialog" role="document">
                        <div class="modal-content">
                           <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLongTitle">Edit Cheque Payment</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                              </button>
                           </div>
                           <div class="modal-body">
                              <form method="Post" action="/admin/chequeedit">
                             @csrf
                              <input type="hidden" name="bill_id" value="{{$bill->id}}"/>
                                 <div class="form-row">
                                    <div class="mt-4 col">
                                       <x-label for="deactivate_reason" :value="__(' Change Status ')" />
                                       <select  class="form-control" name="status">
                                       <option value="">Select Status</option>
                                       <option value="paid">Paid</option>
                                       <option value="unpaid">Unpaid</option>
                                       </select>
                                    </div>
                                 </div>
                                 <div class="modal-footer">
                                    <div class="flex items-center justify-end mt-4">
                                       <x-button class="ml-4">
                                          {{ __('Save') }}
                                       </x-button>
                                    </div>
                                 </div>
                              </form>
                           </div>
                        </div>
                     </div>
                  </div>

    @endforeach
  </tbody>
</table>
             
            </div>
        </div>
    </div>

    <script>
      // jQuery.noConflict();
    jQuery(document).ready(function(e) {
      e.noConflict();
      jQuery('#table').DataTable();
      jQuery('.alert-success').hide('slide', {direction: 'right'}, 10000);

} );
    </script>
</x-app-layout>