routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PartyController;
use App\Http\Controllers\MeterController;
use App\Http\Controllers\ConnectionController;
use App\Http\Controllers\ConnectionChargeController;
use App\Http\Controllers\CreateBillController;
use App\Http\Controllers\ExpencesAccountController;
use App\Http\Controllers\ExpencesBillController;
use App\Http\Controllers\CustomBillController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ConnectionType;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\NocController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\DailyReportController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');

})->name('home');;


// Route::get('/dashboard', function () {
//     // return view('dashboard');
// })->middleware(['auth'])->name('dashboard');
//  Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth','2fa'])->name('dashboard');
 Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth'])->name('dashboard');

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){

    Route::resource('/party', PartyController::class);
    Route::resource('/meter', MeterController::class);
    Route::resource('/conn', ConnectionController::class);
    Route::resource('/createbill', CreateBillController::class);
    Route::get('/conndetails/{id}', [ConnectionController::class,'details'])->name('conndetails');
    Route::get('charges',[ConnectionChargeController::class, 'index'])->name('charge');
    Route::post('savecharge',[ConnectionChargeController::class, 'store'])->name('savecharge');
    Route::get('/viewbill/{id}', [CreateBillController::class,'viewbill'])->name('viewbill');
    // Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');
    Route::post('adminbillpay', [CreateBillController::class,'adminbillpay'])->name('adminbillpay');
    Route::get('/billbyconn/{id}', [CreateBillController::class,'billbyconn'])->name('billbyconn');
    Route::resource('/expensesaccount', ExpencesAccountController::class);
    // Route::get('/expencesbill/{id}', [ExpencesAccountController::class,'expencesbill'])->name('expencesbill');
    Route::resource('/expencesbill', ExpencesBillController::class);
    Route::get('/expencesbilllist/{id}', [ExpencesBillController::class,'list'])->name('expencesbilllist');
    Route::resource('/custombill', CustomBillController::class);
    Route::resource('/conn-type', ConnectionType::class);
    Route::post('custombillpay', [CreateBillController::class,'custombillpay'])->name('custombillpay');
    Route::get('adminprofile', [HomeController::class,'viewprofile'])->name('adminprofile');
    Route::post('settlement', [PartyController::class,'settlement'])->name('settlement');
    Route::get('settlement/{id}', [PartyController::class,'settlementdetail'])->name('settlementdetail');
    Route::post('updateprofile', [HomeController::class,'updateprofile'])->name('updateprofile');
    Route::get('reports', [ExpencesBillController::class,'reports'])->name('reports');
    Route::post('viewreport', [ExpencesBillController::class,'viewreport'])->name('viewreport');
    Route::get('noclist', [NocController::class,'noclist'])->name('noclist');
    Route::get('shownoc/{id}', [NocController::class,'show'])->name('shownoc');
    Route::post('update-noc', [NocController::class,'update_noc'])->name('update-noc');
    Route::get('downloadnoc/{id}', [NocController::class,'createPDF'])->name('downloadnoc');
    Route::get('transactions', [HomeController::class,'transactions'])->name('transactions');
    Route::get('seeall', [NocController::class,'seeall'])->name('seeall');
    Route::get('updatenoti', [NocController::class,'updatenoti'])->name('updatenoti');
    Route::post('getemailbyconn', [ConnectionController::class,'getemailbyconn'])->name('getemailbyconn');
    Route::get('seeallexpances', [ExpencesAccountController::class,'seeallexpances'])->name('seeallexpances');
    Route::post('getallexpances', [ExpencesAccountController::class,'getallexpances'])->name('getallexpances');
    Route::post('getslectbox', [ConnectionType::class,'getslectbox'])->name('getslectbox');
    Route::post('chequeedit', [CreateBillController::class,'chequeedit'])->name('chequeedit');
    Route::resource('counter', DailyReportController::class);
    Route::post('applynoc', [NocController::class,'applynoc'])->name('applynoc');
    Route::get('ledger', [ConnectionController::class,'ledger'])->name('ledger');


});
Route::get('conn-type',[ConnectionType::class, 'index'])->middleware(['auth'])->name('conn-type');
Route::get('party',[PartyController::class, 'index'])->middleware(['auth'])->name('party');
Route::get('meter',[MeterController::class, 'index'])->middleware(['auth'])->name('meter');
Route::get('conn',[ConnectionController::class, 'index'])->middleware(['auth'])->name('conn');
Route::get('createbill',[CreateBillController::class, 'index'])->middleware(['auth'])->name('createbill');
Route::get('paybill',[CreateBillController::class, 'paybill'])->middleware(['auth'])->name('paybill');
Route::post('getconnection',[ConnectionController::class, 'getconnection'])->middleware(['auth'])->name('getconnection');
Route::post('getconnectionbyparty',[ConnectionController::class, 'getconnectionbyparty'])->middleware(['auth'])->name('getconnectionbyparty');
Route::post('getconnectionbyconn',[ConnectionController::class, 'getconnectionbyconn'])->middleware(['auth'])->name('getconnectionbyconn');
Route::get('partybill',[ConnectionController::class, 'partybill'])->middleware(['auth'])->name('partybill');
Route::post('getallconnection',[ConnectionController::class, 'getallconnection'])->middleware(['auth'])->name('getallconnection');
Route::post('getbilldetail', [CreateBillController::class,'getbilldetail'])->name('getbilldetail');
Route::get('/expensesaccount', [ExpencesAccountController::class,'index'])->name('expensesaccount');
Route::get('/expencesbill', [ExpencesBillController::class,'index'])->name('expencesbill');
Route::get('/custombill', [CustomBillController::class,'index'])->name('custombill');
Route::get('/complete-registration', [RegisteredUserController::class,'completeRegistration']);
Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');
Route::get('/login', [CustomerController::class, 'index'])
                ->middleware('guest')
                ->name('login');
Route::post('/customerlogin', [CustomerController::class, 'login'])
                ->middleware('guest')
                ->name('customerlogin');

Route::group(['prefix'=>'customer','middleware'=>['customer']],function(){
    Route::get('/dashboard', [HomeController::class,'customerdashboard']);
    Route::get('bill/{id?}/', [HomeController::class,'customerbill']);
    Route::get('paynow/{id}/', [PaymentController::class,'paynnow']);
    Route::resource('noc', NocController::class);
    Route::get('records/{id?}', [CustomerController::class,'records']);
    Route::get('downloadnoc/{id}', [NocController::class,'downloadnoc'])->name('downloadnoc');
    Route::get('profile', [CustomerController::class,'profile'])->name('profile');
    Route::post('updateprofile', [CustomerController::class,'updateprofile'])->name('updateprofile');
    // Route::get('verifymail/{email}', [CustomerController::class,'verifymail'])->name('verifymail');
    Route::post('updatedata', [CustomerController::class,'updatedata'])->name('updatedata');
    Route::post('resend', [CustomerController::class,'resend'])->name('resend');
    // Route::get('verifymobile/{mobile}', [CustomerController::class,'verifymobile'])->name('verifymobile');
    Route::get('shownocc/{id}', [NocController::class,'customershownoc'])->name('shownocc');
    Route::get('checkmail', [CustomerController::class,'checkmail'])->name('checkmail');
    Route::get('checkmob', [CustomerController::class,'checkmob'])->name('checkmob');
    Route::get('/viewrecipts/{id}', [HomeController::class,'viewrecipt'])->name('viewrecipt');
    Route::get('newconn', [HomeController::class,'newconn'])->name('newconn');


});
Route::get('/customer-reg', [CustomerController::class, 'registration'])
                ->middleware('guest')
                ->name('customer-reg');
Route::get('/cu-reg', [CustomerController::class, 'register'])
->middleware('guest')
->name('cu-reg');

Route::get('/housing-reg', [CustomerController::class, 'housing_register'])
->middleware('guest')
->name('housing-reg');

Route::post('/storecustomer', [CustomerController::class, 'store'])
->middleware('guest')
->name('storecustomer');
Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');


// Route::post('subscribe-cancel', [
//     'as' => 'subscribe-cancel',
//     'uses' => 'PaymentController@SubscribeCancel'
// ]);

// Route::post('subscribe-response', [
//     'as' => 'subscribe-response',
//     'uses' => 'PaymentController@SubscribeResponse'
// ]);
Route::post('subscribe-response', [PaymentController::class,'SubscribeResponse']);
Route::get('/paysuccess', [PaymentController::class,'paysuccess'])->name('paysuccess');
Route::get('/sendmail', [EmailController::class,'sendmail'])->name('sendmail');
Route::get('/verifyemail', [EmailController::class,'verifyemail'])->name('verifyemail');
Route::post('/confirmemail', [EmailController::class,'confirmemail'])->name('confirmemail');

app/Models/CustomBill.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CustomBill extends Model
{
    use HasFactory;
    protected $fillable = [
        'connection_id',
        'data',
        'amount',
        'total',
        'meter_id',
        'meter_status',
        'paid_status',
        'paid_date',
        'title',
        'debit',
        'credit',
        'voucher_no',
        'pay_amount',
        'rem_amount',
        'pay_by',
        'check_no',
        'previousdue',
        'note',

    ];
    public function conn(){
        return $this->hasOne(Connection::class,'id','connection_id');
    }
}

app/Http/Controllers/CustomBillController.php
<?php

namespace App\Http\Controllers;

use App\Models\CustomBill;
use Illuminate\Http\Request;
use DB;
use App\Models\Connection;
use App\Models\Meter;
use Illuminate\Support\Facades\Validator;
use Carbon\Carbon;
class CustomBillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bills = CustomBill::orderBy('id', 'DESC')->get();
        return view('custombill.list',['bills'=>$bills,]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $connections = Connection::orderBy('id', 'DESC')->get();
        return view('custombill.add',['connections'=>$connections]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        Validator::make($request->all(), [
            'data' => 'required',
            'amount' => 'required',
            'connection_id' => 'required',

            ])->validate();
           $meter =  Meter::where('connections_id',$request->connection_id)->orderBy('id', 'DESC')->first();
      $lastest = CustomBill::latest('id')->first();
    //   dd($lastest);
    if(empty($lastest)){
       $vno =  0;   
    }else{
        $vno =  $lastest->id; 
    }
    if(!empty($lastest)){
    if($lastest->paid_status=='unpaid'){
        $predue = $lastest->total;
    }else{
        $predue= 0;
    }
}else{
    $predue= 0;

}
           $billid = CustomBill::create([
            'data' => json_encode($request->data),
            'amount' =>json_encode($request->amount),
            'total' => array_sum($request->amount)+$predue,
            'previousdue' => $predue,
            'connection_id'=>$request->connection_id,
            'meter_id'=>$meter->id,
            'meter_status'=>$meter->status,
            'title'=>$request->title,
            'voucher_no'=>'cus'.++$vno,
            'paid_status'=>'unpaid',
            'note'=>$request->note,

        ]);
        // $connection = Connection::find($request->connection_id);
        // $bill_data =  CustomBill::find($billid->id);
        // $total = array_sum($request->amount);
        // if($connection->credit>=$total){
        //     $bill_data->pay_by = 'credit';
        //     $bill_data->paid_date = date('Y-m-d H:i:s');
        //     $bill_data->paid_status='paid';	
        //     $bill_data->credit=$total;	
        //     $bill_data->debit=0;
        //     $bill_data->save();
        //     $connection->credit = abs($connection->credit - array_sum($request->amount));
        //     $connection->debit =0;
        // }else{
        //     $bill_data->debit=$total;	
        //     $bill_data->credit=0;
        //     $bill_data->save();

        // $connection->debit = $connection->debit + array_sum($request->amount);
        // $connection->credit =0;
        //  } 
        //  $connection->save();
        return redirect()->route('custombill')->with('status', 'Bill added  succesfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\CustomBill  $customBill
     * @return \Illuminate\Http\Response
     */
    public function show( $customBill)
    {
       $customBill = CustomBill::find($customBill);
      $lastunpaid =  CustomBill::where('id','<',$customBill->id)->where('paid_status','unpaid')->first();
       return view('custombill.view',['bill'=>$customBill,'lastunpaid'=>$lastunpaid]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\CustomBill  $customBill
     * @return \Illuminate\Http\Response
     */
    public function edit(CustomBill $customBill)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\CustomBill  $customBill
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CustomBill $customBill)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\CustomBill  $customBill
     * @return \Illuminate\Http\Response
     */
    public function destroy(CustomBill $customBill)
    {
        //
    }
}

resources/views/custombill/add.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="row">
         <div class="col-md-10">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
               {{ __('Add Custom Bill') }}
            </h2>
         </div>
         <div class="col-md-2">
            <a class="btn btn-primary" href="{{ route('custombill') }}">
            {{ __('Custom Bill List') }}
            </a>
         </div>
      </div>
   </x-slot>
   <div class="py-12">
      <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
         <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6 bg-white border-b border-gray-200">
               <x-auth-validation-errors class="mb-4" :errors="$errors" />
               <fieldset class="scheduler-border">
                  <legend class="scheduler-border">Add Custom Bill:</legend>
                  <form method="POST" action="{{ route('custombill.store') }}">
                     @csrf
                     <div class="form-row">
                      <div class="mt-4 col-md-5">
                                 <x-label for="conn_no" :value="__(' Connection No')" />
                                 <!-- <x-input id="conn_no" class="block mt-1 w-full"
                                    type="text" name="conn_no" :value="old('conn_no')" required   /> -->
                                    <select id="conn_no" class="form-control" name="connection_id" required>
                              <option value="">Choose...</option>
                              @foreach($connections as $connection)
                              <option value="{{$connection->id}}">{{$connection->conn_no}}</option>
                            
                              @endforeach
                           </select>
                        </div>
                        <div class="mt-4 col-md-5">
                                 <label for="data">Title</label>
                                 <x-input  class="form-control data"
                                    type="text" name="title"  required   />
                              </div>
                              </div>
             <div id="add">
                      <div class="form-row" >              
                              <!--Connection  Name -->
                              <div class="mt-4 col-md-5">
                                 <label for="data">Reason</label>
                                 <x-input  class="form-control data"
                                    type="text" name="data[]"  required   />
                              </div>
                              <div class="mt-4 col-md-5">
                                 <label for="amount">Amount</label>
                                 <x-input  class="form-control amount"
                                    type="number" name="amount[]"  required   />
                              </div>
                              <div class="mt-4 pt-2 col-md-2">               <button id="plus" type="button" class="btn btn-primary mt-4"><i class="fa fa-plus" aria-hidden="true"></i></button>
</div>
                        </div>
                        </div>
                        <div class="mt-4  col-md-5">
                                 <label for="data">Note</label>
                                 <textarea rows="5" class="form-control data"
                                     name="note"    ></textarea>
                              </div>
                        </fieldset>
                     </fieldset>
                     <div class="flex items-center justify-end mt-4">
                        <x-button class="ml-4">
                           {{ __('Save') }}
                        </x-button>
                     </div>
                  </form>
               </fieldset>
            </div>
         </div>
      </div>
   </div>
   <script>
     $('#plus').on('click', function () { 
//   alert("hello");
  // Adding a row inside the tbody. 
  $('#add').append(`<div class="form-row"> 
       <div class="col-md-5"><label for="data">Reason</label>
         <input  class="form-control data" type="text" name="data[]"  required   />
      </div>
      <div class="col-md-5"><label for="amount">Amount</label>
         <input  class="form-control amount" type="number" name="amount[]"  required   />
      </div>
      <div class="col-md-2">
          <button class="btn btn-danger mt-30 remove"
            type="button"><i class="fa fa-times" aria-hidden="true"></i>
       </button> 
          </div> 
        </div>`); 
});

$(document).on('click','.remove', function () { 
$(this).closest('.form-row').remove()
});
   </script>
</x-app-layout>

resources/views/custombill/list.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="row">
         <div class="col-md-10">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
               {{ __('Custom Bill') }}
            </h2>
         </div>
         <div class="col-md-2">
            <a class="btn btn-primary" href="{{ route('custombill.create') }}">
            {{ __('Add Custom Bill') }}
            </a>
         </div>
      </div>
   </x-slot>
   <div class="col-md-12">
    <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-3" style="position:absolute; right:0">
    @if (session('status'))
      <div class="alert alert-success">
          <p class="msg"> <?php echo  session("status"); ?></p>
      </div>
    @endif
     </div>
     </div></div>
   <div class="py-12">
      <div class="py-12 bg-white max-w-7xl mx-auto sm:px-6 lg:px-8">
         <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg table-responsive">
            <table class="table" id="table">
               <thead>
                  <tr>
                     <th scope="col">#</th>
                     <th scope="col">Conn No</th>
                     <th scope="col">Voucher No</th>
                      <th scope="col">Title</th>
                     <th scope="col">Total</th>
                     <th scope="col">Paid Status</th>
                     <th scope="col">Action</th>
                  </tr>
               </thead>
               <tbody>
                  @php $i=1; @endphp
                  @foreach($bills as $bill)
                  <tr>
                     <th scope="row">{{$i++}}</th>
                     <th scope="row">{{$bill->conn->conn_no}}</th>
                     <td>{{$bill->voucher_no}}</td>
                      <td>{{$bill->title}}</td>
                     <td>{{$bill->total}}</td>
                     <td>{{$bill->paid_status}}</td>
                     <td><a href="{{route('custombill.show',$bill->id)}}" ><i class="fa fa-eye" aria-hidden="true"></i></a></td>
                  </tr>
              
                  @endforeach
               </tbody>
            </table>
         </div>
      </div>
   </div>
   <script>
      // jQuery.noConflict();
      jQuery(document).ready(function(e) {
      e.noConflict();
      jQuery('#table').DataTable();
      jQuery('.alert-success').hide('slide', {direction: 'right'}, 10000);

      } );
   </script>
</x-app-layout>