routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PartyController;
use App\Http\Controllers\MeterController;
use App\Http\Controllers\ConnectionController;
use App\Http\Controllers\ConnectionChargeController;
use App\Http\Controllers\CreateBillController;
use App\Http\Controllers\ExpencesAccountController;
use App\Http\Controllers\ExpencesBillController;
use App\Http\Controllers\CustomBillController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ConnectionType;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\NocController;
use App\Http\Controllers\EmailController;
use App\Http\Controllers\DailyReportController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');

})->name('home');;


// Route::get('/dashboard', function () {
//     // return view('dashboard');
// })->middleware(['auth'])->name('dashboard');
//  Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth','2fa'])->name('dashboard');
 Route::get('/dashboard', [HomeController::class,'index'])->middleware(['auth'])->name('dashboard');

Route::group(['prefix'=>'admin','middleware'=>['auth']],function(){

    Route::resource('/party', PartyController::class);
    Route::resource('/meter', MeterController::class);
    Route::resource('/conn', ConnectionController::class);
    Route::resource('/createbill', CreateBillController::class);
    Route::get('/conndetails/{id}', [ConnectionController::class,'details'])->name('conndetails');
    Route::get('charges',[ConnectionChargeController::class, 'index'])->name('charge');
    Route::post('savecharge',[ConnectionChargeController::class, 'store'])->name('savecharge');
    Route::get('/viewbill/{id}', [CreateBillController::class,'viewbill'])->name('viewbill');
    // Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');
    Route::post('adminbillpay', [CreateBillController::class,'adminbillpay'])->name('adminbillpay');
    Route::get('/billbyconn/{id}', [CreateBillController::class,'billbyconn'])->name('billbyconn');
    Route::resource('/expensesaccount', ExpencesAccountController::class);
    // Route::get('/expencesbill/{id}', [ExpencesAccountController::class,'expencesbill'])->name('expencesbill');
    Route::resource('/expencesbill', ExpencesBillController::class);
    Route::get('/expencesbilllist/{id}', [ExpencesBillController::class,'list'])->name('expencesbilllist');
    Route::resource('/custombill', CustomBillController::class);
    Route::resource('/conn-type', ConnectionType::class);
    Route::post('custombillpay', [CreateBillController::class,'custombillpay'])->name('custombillpay');
    Route::get('adminprofile', [HomeController::class,'viewprofile'])->name('adminprofile');
    Route::post('settlement', [PartyController::class,'settlement'])->name('settlement');
    Route::get('settlement/{id}', [PartyController::class,'settlementdetail'])->name('settlementdetail');
    Route::post('updateprofile', [HomeController::class,'updateprofile'])->name('updateprofile');
    Route::get('reports', [ExpencesBillController::class,'reports'])->name('reports');
    Route::post('viewreport', [ExpencesBillController::class,'viewreport'])->name('viewreport');
    Route::get('noclist', [NocController::class,'noclist'])->name('noclist');
    Route::get('shownoc/{id}', [NocController::class,'show'])->name('shownoc');
    Route::post('update-noc', [NocController::class,'update_noc'])->name('update-noc');
    Route::get('downloadnoc/{id}', [NocController::class,'createPDF'])->name('downloadnoc');
    Route::get('transactions', [HomeController::class,'transactions'])->name('transactions');
    Route::get('seeall', [NocController::class,'seeall'])->name('seeall');
    Route::get('updatenoti', [NocController::class,'updatenoti'])->name('updatenoti');
    Route::post('getemailbyconn', [ConnectionController::class,'getemailbyconn'])->name('getemailbyconn');
    Route::get('seeallexpances', [ExpencesAccountController::class,'seeallexpances'])->name('seeallexpances');
    Route::post('getallexpances', [ExpencesAccountController::class,'getallexpances'])->name('getallexpances');
    Route::post('getslectbox', [ConnectionType::class,'getslectbox'])->name('getslectbox');
    Route::post('chequeedit', [CreateBillController::class,'chequeedit'])->name('chequeedit');
    Route::resource('counter', DailyReportController::class);
    Route::post('applynoc', [NocController::class,'applynoc'])->name('applynoc');
    Route::get('ledger', [ConnectionController::class,'ledger'])->name('ledger');


});
Route::get('conn-type',[ConnectionType::class, 'index'])->middleware(['auth'])->name('conn-type');
Route::get('party',[PartyController::class, 'index'])->middleware(['auth'])->name('party');
Route::get('meter',[MeterController::class, 'index'])->middleware(['auth'])->name('meter');
Route::get('conn',[ConnectionController::class, 'index'])->middleware(['auth'])->name('conn');
Route::get('createbill',[CreateBillController::class, 'index'])->middleware(['auth'])->name('createbill');
Route::get('paybill',[CreateBillController::class, 'paybill'])->middleware(['auth'])->name('paybill');
Route::post('getconnection',[ConnectionController::class, 'getconnection'])->middleware(['auth'])->name('getconnection');
Route::post('getconnectionbyparty',[ConnectionController::class, 'getconnectionbyparty'])->middleware(['auth'])->name('getconnectionbyparty');
Route::post('getconnectionbyconn',[ConnectionController::class, 'getconnectionbyconn'])->middleware(['auth'])->name('getconnectionbyconn');
Route::get('partybill',[ConnectionController::class, 'partybill'])->middleware(['auth'])->name('partybill');
Route::post('getallconnection',[ConnectionController::class, 'getallconnection'])->middleware(['auth'])->name('getallconnection');
Route::post('getbilldetail', [CreateBillController::class,'getbilldetail'])->name('getbilldetail');
Route::get('/expensesaccount', [ExpencesAccountController::class,'index'])->name('expensesaccount');
Route::get('/expencesbill', [ExpencesBillController::class,'index'])->name('expencesbill');
Route::get('/custombill', [CustomBillController::class,'index'])->name('custombill');
Route::get('/complete-registration', [RegisteredUserController::class,'completeRegistration']);
Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');
Route::get('/login', [CustomerController::class, 'index'])
                ->middleware('guest')
                ->name('login');
Route::post('/customerlogin', [CustomerController::class, 'login'])
                ->middleware('guest')
                ->name('customerlogin');

Route::group(['prefix'=>'customer','middleware'=>['customer']],function(){
    Route::get('/dashboard', [HomeController::class,'customerdashboard']);
    Route::get('bill/{id?}/', [HomeController::class,'customerbill']);
    Route::get('paynow/{id}/', [PaymentController::class,'paynnow']);
    Route::resource('noc', NocController::class);
    Route::get('records/{id?}', [CustomerController::class,'records']);
    Route::get('downloadnoc/{id}', [NocController::class,'downloadnoc'])->name('downloadnoc');
    Route::get('profile', [CustomerController::class,'profile'])->name('profile');
    Route::post('updateprofile', [CustomerController::class,'updateprofile'])->name('updateprofile');
    // Route::get('verifymail/{email}', [CustomerController::class,'verifymail'])->name('verifymail');
    Route::post('updatedata', [CustomerController::class,'updatedata'])->name('updatedata');
    Route::post('resend', [CustomerController::class,'resend'])->name('resend');
    // Route::get('verifymobile/{mobile}', [CustomerController::class,'verifymobile'])->name('verifymobile');
    Route::get('shownocc/{id}', [NocController::class,'customershownoc'])->name('shownocc');
    Route::get('checkmail', [CustomerController::class,'checkmail'])->name('checkmail');
    Route::get('checkmob', [CustomerController::class,'checkmob'])->name('checkmob');
    Route::get('/viewrecipts/{id}', [HomeController::class,'viewrecipt'])->name('viewrecipt');
    Route::get('newconn', [HomeController::class,'newconn'])->name('newconn');


});
Route::get('/customer-reg', [CustomerController::class, 'registration'])
                ->middleware('guest')
                ->name('customer-reg');
Route::get('/cu-reg', [CustomerController::class, 'register'])
->middleware('guest')
->name('cu-reg');

Route::get('/housing-reg', [CustomerController::class, 'housing_register'])
->middleware('guest')
->name('housing-reg');

Route::post('/storecustomer', [CustomerController::class, 'store'])
->middleware('guest')
->name('storecustomer');
Route::get('/viewrecipt/{id}', [CreateBillController::class,'viewrecipt'])->name('viewrecipt');


// Route::post('subscribe-cancel', [
//     'as' => 'subscribe-cancel',
//     'uses' => 'PaymentController@SubscribeCancel'
// ]);

// Route::post('subscribe-response', [
//     'as' => 'subscribe-response',
//     'uses' => 'PaymentController@SubscribeResponse'
// ]);
Route::post('subscribe-response', [PaymentController::class,'SubscribeResponse']);
Route::get('/paysuccess', [PaymentController::class,'paysuccess'])->name('paysuccess');
Route::get('/sendmail', [EmailController::class,'sendmail'])->name('sendmail');
Route::get('/verifyemail', [EmailController::class,'verifyemail'])->name('verifyemail');
Route::post('/confirmemail', [EmailController::class,'confirmemail'])->name('confirmemail');

app/Models/Meter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Meter extends Model
{
    use HasFactory;
    protected $fillable = [
        'meter_no',
        'connections_id',
        'installation_date',
        'status',
        'current_unit',
        'innital_meter_reading',
        'closing_unit',
        'deactivate_date',
    ];

    protected $guarded = array('connections_id');

    public function conn(){
        return $this->hasOne(Connection::class,'id','connections_id');
    }

    public function connection()
    {
        return $this->belongsTo(Connection::class,'connections_id','id');
    }

}

app/Http/Controllers/MeterController.php
<?php

namespace App\Http\Controllers;

use App\Models\Meter;
use App\Models\Connection;
use Illuminate\Http\Request;
use DB;
class MeterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $meters = Meter::orderBy('id', 'DESC')->get();
        return view('meter.list',['meters'=>$meters]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
      
        $connections = Connection::orderBy('id', 'DESC')->get();
        return view('meter.add',['connections'=>$connections]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'conn_no' => 'required',
            'meter_no' => 'required',
            'innital_meter_reading' => 'required',
            'installation_date' => 'required',
            ]);
      $meterdata = Connection::where('id',$request->conn_no)->first();
      if(empty( $meterdata)) {
        return back()->with('error', 'error');

      }    
      $meter_test_copy='';
      $application_copy='';
      if($request->meter_test_copy)
      {
          $images = $request->file('meter_test_copy');
          $destinationPath = public_path('/meter_test_copy'); 

           // $imageed = $request->file('pdffile')[$key];
              $meter_test_copy = time().'.'.$images->getClientOriginalExtension(); 
              $image->move($destinationPath, $meter_test_copy); 

      }
      if($request->application_copy)
      {
          $image = $request->file('application_copy');
          $destinationPath = public_path('/application_copy'); 

           // $imageed = $request->file('pdffile')[$key];
              $application_copy = time().'.'.$image->getClientOriginalExtension(); 
              $image->move($destinationPath, $application_copy); 

      }
  
      $meterid = Meter::create([
                'connections_id' => $request->conn_no,
                'meter_no' => $request->meter_no,
                'installation_date' => date('y-m-d h:i:s',strtotime($request->installation_date)),
                'party_types_id' => $request->party_types_id,
                'status' => $request->status,
                'innital_meter_reading' => $request->innital_meter_reading,
                'current_unit' => $request->innital_meter_reading,
                'meter_test_copy' => $meter_test_copy,
                'appliaction_copy' => $application_copy,
            ]);

            return redirect()->route('meter')->with('status', 'Meter added  succesfully');
            // return back()->with('status', 'success');
    
            // return redirect()->route('meter');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Meter  $meter
     * @return \Illuminate\Http\Response
     */
    public function show( $meter)
    {
        // $unit = $_GET['closing_unit'];
        $unit = Meter::find($meter);
        Meter::where('id', $meter)
        ->update(['status' => 'inactive','closing_unit'=>$unit->current_unit,'deactivate_date'=>date('Y-m-d H:i:s')]);
        return redirect()->route('meter');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Meter  $meter
     * @return \Illuminate\Http\Response
     */
    public function edit(Meter $meter)
    {
        $connections = Connection::all();
        return view('meter.edit',['meter'=>$meter,'connections'=>$connections]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Meter  $meter
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Meter $meter)
    {
        $request->validate([
            'conn_no' => 'required',
            'meter_no' => 'required',
            'innital_meter_reading' => 'required',
            'installation_date' => 'required',
            ]);

            // $meter->connections_id = $request->conn_no;
            $meter->meter_no = $request->meter_no;
            $meter->installation_date =date('y-m-d h:i:s',strtotime($request->installation_date));
            $meter->status =$request->status;
            $meter->meter_test_copy =$request->meter_test_copy;
            $meter->appliaction_copy =$request->application_copy;
            $meter->innital_meter_reading =$request->innital_meter_reading;
            $meter->save();
            return redirect()->route('meter')->with('status', 'Meter  updated succesfully');

               
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Meter  $meter
     * @return \Illuminate\Http\Response
     */
    public function destroy(Meter $meter)
    {
        //
    }
}

resources/views/meter/add.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="row">
         <div class="col-md-10">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
               {{ __('Add Meter') }} (Only if last meter is inactive)
            </h2>
         </div>
         <div class="col-md-2">
            <a class="btn btn-primary" href="{{ route('meter') }}">
            {{ __('Meter List') }}
            </a>
         </div>
      </div>
   </x-slot>
   <div class="py-12">
      <div class="max-w-5xl mx-auto sm:px-6 lg:px-8">
         <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6 bg-white border-b border-gray-200">
            @if (session('status') == 'success')
            <div class="mb-4 font-medium text-sm text-green-600">
               <h5> {{ __('.Data Save Succesfully') }}</h5>
            </div>
            @endif

            @if (session('error')=='error')
            <div class="mb-4 font-medium text-sm text-green-600">
               <h5> {{ __('.Connection Not Found') }}</h5>
            </div>
            @endif
               <x-auth-validation-errors class="mb-4" :errors="$errors" />
               <fieldset class="scheduler-border">
                  <legend class="scheduler-border">Add Meter:</legend>
                  <form method="POST" action="{{ route('meter.store') }}">
                     @csrf
             
                      <div class="form-row">
                      <div class="mt-4 col">
                                 <x-label for="conn_no" :value="__(' Connection No')" />
                                 <!-- <x-input id="conn_no" class="block mt-1 w-full"
                                    type="text" name="conn_no" :value="old('conn_no')" required   /> -->
                                    <select id="conn_no" class="form-control" name="conn_no" required>
                              <option value="">Choose...</option>
                              @foreach($connections as $connection)
                               @if($connection->meter->status=='inactive')
                              <option value="{{$connection->id}}">{{$connection->conn_no}}</option>
                            @endif
                              @endforeach
                           </select>
                              </div>
                              <!--Connection  Name -->
                              <div class="mt-4 col">
                                 <x-label for="meter_no" :value="__(' Add Meter No')" />
                                 <x-input id="meter_no" class="block mt-1 w-full"
                                    type="text" name="meter_no" :value="old('meter_no')" required   />
                              </div>
                              <!-- <x-input id="date" class="block mt-1 w-full" type="text" name="date" :value="old('date')" required /> -->
                              <!-- Date -->
                              <div class="mt-4 col">
                                 <x-label for="installation_date" :value="__('Date of Installation')" />
                                 <x-input id="installation_date" class="block mt-1 w-full"
                                    type="date" max="{{date('Y-m-d')}}" format="dd-mm-yyyy" name="installation_date" :value="old('installation_date')" required   />
                              </div>
                           </div>
                           <div class="form-row">
                              <!--Connection  Name -->
                              <div class="mt-4 col">
                                 <x-label for="meter_test_copy" :value="__(' Copy of Meter Test')" />
                                 <x-input id="meter_test_copy" class="block mt-1 w-full"
                                    type="file" name="meter_test_copy" :value="old('meter_test_copy')"    />
                              </div>
                              <!-- <x-input id="date" class="block mt-1 w-full" type="text" name="date" :value="old('date')" required /> -->
                              <!-- Date -->
                              <div class="mt-4 col">
                                 <x-label for="application_copy" :value="__('Copy of Application')" />
                                 <x-input id="application_copy" class="block mt-1 w-full"
                                    type="file" name="application_copy" :value="old('application_copy')"    />
                              </div>
                           </div>
                           <div class="form-row">
                              <!--Connection  Name -->
                              <div class="mt-4 col">
                                 <x-label for="meter_test_copy" :value="__(' Meter Status')" />
                                 <div class="form-check">
                                    <input class="form-check-input" type="radio" name="status" id="active" value="active" checked>
                                    <label class="form-check-label" for="gridRadios1">
                                    Active
                                    </label>
                                 </div>
                                 <!-- <div class="form-check">
                                    <input class="form-check-input" type="radio" name="status" id="inactive" value="inactive">
                                    <label class="form-check-label" for="gridRadios1">
                                    Inactive
                                    </label>
                                 </div> -->
                              </div>
                              <!-- <x-input id="date" class="block mt-1 w-full" type="text" name="date" :value="old('date')" required /> -->
                              <!-- Date -->
                              <div class="mt-4 col">
                                 <x-label for="innital_meter_reading" :value="__('Initial Mete Reading')" />
                                 <x-input id="innital_meter_reading" class="block mt-1 w-full"
                                    type="number" min="0" name="innital_meter_reading" :value="old('innital_meter_reading')" required   />
                              </div>
                           </div>
                        </fieldset>
                     </fieldset>
                     <div class="flex items-center justify-end mt-4">
                        <x-button class="ml-4">
                           {{ __('Save') }}
                        </x-button>
                     </div>
                  </form>
               </fieldset>
            </div>
         </div>
      </div>
   </div>
</x-app-layout>

resources/views/meter/list.blade.php
<x-app-layout>
   <x-slot name="header">
      <div class="row">
         <div class="col-md-10">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
               {{ __('Meter') }}
            </h2>
         </div>
         <div class="col-md-2">
            <a class="btn btn-primary" href="{{ route('meter.create') }}">
            {{ __('Add Meter') }}
            </a>
         </div>
      </div>
   </x-slot>
   <div class="col-md-12">
    <div class="row">
    <div class="col-md-9"></div>
    <div class="col-md-3" style="position:absolute; right:0">
    @if (session('status'))
      <div class="alert alert-success">
          <p class="msg"> <?php echo  session("status"); ?></p>
      </div>
    @endif
     </div>
     </div></div>
   <div class="py-12">
      <div class="py-12 bg-white max-w-7xl mx-auto sm:px-6 lg:px-8">
         <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg table-responsive">
            <table class="table" id="table">
               <thead>
                  <tr>
                     <th scope="col">#</th>
                     <th scope="col">Status</th>
                     <th scope="col">Connection No</th>
                     <th scope="col">Meter No</th>
                     <th scope="col">Current Reading</th>
                     <th scope="col">Date</th>
                     <th scope="col">Action</th>
                  </tr>
               </thead>
               <tbody>
                  @php $i=1; @endphp
                  @foreach($meters as $meter)
                  <tr>
                     <th scope="row">{{$i++}}</th>
                     <td>{{$meter->status}}</td>
                     <td>@if(isset($meter->conn->conn_no)){{$meter->conn->conn_no}}@else ------ @endif</td>
                     <td>{{$meter->meter_no}}</td>
                     <!-- <td>@if(isset($meter->connection->mybill)){{$meter->connection->mybill->unit}}@endif</td> -->
                        <td>{{$meter->current_unit}}</td>
                     <td>{{date('d-m-y',strtotime($meter->installation_date))}}</td>
                     <td>
                     <a href="{{ route('meter.edit',$meter->id) }}"><i class="fa fa-pencil"></i></a>
                        @if($meter->status=='active') 
                        <!-- <a href="#"  data-toggle="modal" data-target="#edit{{$i}}"><i class="fa fa-trash"></i></a> -->
                        <a onclick="return confirm('Are you sure want to change status?')" href="{{route('meter.show',$meter->id)}}" type="button btn-sm"><i class="fa fa-trash"></i></a>
                        @else not editable @endif|
                        <a href="#"  data-toggle="modal" data-target="#{{$i}}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                     </td>
                  </tr>
                  <div class="modal fade" id="edit{{$i}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                     <div class="modal-dialog" role="document">
                        <div class="modal-content">
                           <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLongTitle">@if(isset($meter->meter_no)){{$meter->meter_no}}@else ------ @endif</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                              </button>
                           </div>
                           <div class="modal-body">
                              <form method="GET" action="{{route('meter.show',$meter->id)}}">
                                 <div class="form-row">
                                    <div class="mt-4 col">
                                       <x-label for="connection_charge" :value="__(' Closing Unit ')" />
                                       <input  class="block mt-1 w-full form-control"
                                          type="number" name="closing_unit" :value="old('connection_charge')" required   />
                                    </div>
                                 </div>
                                 <div class="modal-footer">
                                    <div class="flex items-center justify-end mt-4">
                                       <x-button class="ml-4">
                                          {{ __('Save') }}
                                       </x-button>
                                    </div>
                                 </div>
                              </form>
                           </div>
                        </div>
                     </div>
                  </div>
                  <!-- Modal -->
                  <div class="modal fade" id="{{$i}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                     <div class="modal-dialog" role="document">
                        <div class="modal-content">
                           <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLongTitle">@if(isset($meter->conn->conn_no)){{$meter->conn->conn_no}}@else ------ @endif</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                              </button>
                           </div>
                           <div class="modal-body">
                              <div class="form-row">
                                 <div class="col-md-6"><span><b>Meter Status:</b>  {{$meter->status}}</span></div>
                                 <div class="col-md-6"><span><b>Connection No:</b> @if(isset($meter->conn->conn_no)){{$meter->conn->conn_no}}@else ------ @endif</span></div>
                                 <div class="col-md-6"><span><b>Meter No:</b>  {{$meter->meter_no}}</span></div>
                                 <div class="col-md-6"><span><b>Innital Reading:</b> {{$meter->innital_meter_reading}}</span></div>
                                 <div class="col-md-6"><span><b>Closing Reading:</b> {{$meter->closing_unit}}</span></div>
                                 <div class="col-md-6"><span><b>Date:</b> {{date('d-m-y',strtotime($meter->installation_date))}}</span></div>
                              </div>
                           </div>
                           <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                           </div>
                        </div>
                     </div>
                  </div>
                  @endforeach
               </tbody>
            </table>
         </div>
      </div>
   </div>
   <script>
      // jQuery.noConflict();
      jQuery(document).ready(function(e) {
      e.noConflict();
      jQuery('#table').DataTable();
      jQuery('.alert-success').hide('slide', {direction: 'right'}, 10000);

      } );
   </script>
</x-app-layout>